version: "3.9"
services:
  php:
    container_name: mvc-php
    build: './docker-php/'
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - backend
  apache:
    container_name: mvc-apache
    build: './docker-apache/'
    depends_on:
      - php
      - mysql
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
  mysql:
    container_name: mvc-sql
    image: mysql:5.6.40
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MY_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}
    networks:
      - backend
networks:
  frontend:
  backend: